import type { BackendOrigin, BackendPort, BackendVessel, IntegratedDecisionResult, MarketSignals, BackendFeasibilityResult, BackendVoyageResult, BackendCongestionResult } from './types';

export const DEMO_ORIGINS: BackendOrigin[] = [
 {id:'australia',region:'Australia',load_port:'Newcastle',latitude:-32.93,longitude:151.78,detour_factor:1.02,typical_cargo:['Coal','Grain'],data_source:'DEMO_BUNDLED'},
 {id:'brazil',region:'Brazil',load_port:'Tubarao',latitude:-20.28,longitude:-40.24,detour_factor:1.04,typical_cargo:['Iron Ore','Bauxite'],data_source:'DEMO_BUNDLED'},
 {id:'indonesia',region:'Indonesia',load_port:'Taboneo',latitude:-3.75,longitude:114.55,detour_factor:1.01,typical_cargo:['Coal','Bauxite'],data_source:'DEMO_BUNDLED'},
 {id:'south-africa',region:'South Africa',load_port:'Richards Bay',latitude:-28.78,longitude:32.04,detour_factor:1.03,typical_cargo:['Coal','Iron Ore'],data_source:'DEMO_BUNDLED'},
 {id:'usa-gulf',region:'USA Gulf',load_port:'New Orleans',latitude:29.95,longitude:-90.07,detour_factor:1.07,typical_cargo:['Grain','Coal'],data_source:'DEMO_BUNDLED'},
];

export const DEMO_PORTS: BackendPort[] = [
 {id:'paradip',name:'Paradip Port',state:'Odisha',latitude:20.27,longitude:86.70,max_draft:18.5,max_loa:300,max_beam:46,berth_capacity:18,cargo_types_supported:['Coal','Iron Ore','Grain','Bauxite','Fertilizer','Limestone'],cargo_handling_rate:42000,max_vessel_size:200000,congestion_index:.42,berth_utilization:.68,turnaround_time:2.6,anchorage_wait_time:.8,operating_status:'OPERATIONAL',restrictions:[],data_source:'DEMO_BUNDLED'},
 {id:'vizag',name:'Visakhapatnam Port',state:'Andhra Pradesh',latitude:17.69,longitude:83.22,max_draft:18,max_loa:295,max_beam:45,berth_capacity:16,cargo_types_supported:['Coal','Iron Ore','Grain','Bauxite'],cargo_handling_rate:39000,max_vessel_size:180000,congestion_index:.36,berth_utilization:.61,turnaround_time:2.4,anchorage_wait_time:.7,operating_status:'OPERATIONAL',restrictions:[],data_source:'DEMO_BUNDLED'},
 {id:'krishnapatnam',name:'Krishnapatnam Port',state:'Andhra Pradesh',latitude:14.25,longitude:80.12,max_draft:18.2,max_loa:300,max_beam:46,berth_capacity:12,cargo_types_supported:['Coal','Grain','Bauxite','Fertilizer'],cargo_handling_rate:36000,max_vessel_size:190000,congestion_index:.29,berth_utilization:.54,turnaround_time:2.2,anchorage_wait_time:.5,operating_status:'OPERATIONAL',restrictions:[],data_source:'DEMO_BUNDLED'},
];

export const DEMO_VESSELS: BackendVessel[] = [
 {id:'handysize',vessel_type:'Handysize',dwt:32000,cargo_capacity:30000,loa:180,beam:28,draft:10,laden_speed:12.5,ballast_speed:13.5,daily_opex:5200,daily_charter_rate:11000,loading_rate:9000,discharge_rate:8000,cargo_types:['Coal','Grain','Fertilizer','Bauxite','Limestone'],data_source:'DEMO_BUNDLED'},
 {id:'supramax',vessel_type:'Supramax',dwt:58000,cargo_capacity:55000,loa:190,beam:32.3,draft:12.8,laden_speed:13.5,ballast_speed:14.5,daily_opex:6000,daily_charter_rate:15500,loading_rate:16000,discharge_rate:14000,cargo_types:['Coal','Iron Ore','Grain','Fertilizer','Bauxite','Limestone'],data_source:'DEMO_BUNDLED'},
 {id:'panamax',vessel_type:'Panamax',dwt:76000,cargo_capacity:72000,loa:229,beam:32.3,draft:14.2,laden_speed:13.5,ballast_speed:14.5,daily_opex:6600,daily_charter_rate:18500,loading_rate:24000,discharge_rate:20000,cargo_types:['Coal','Iron Ore','Grain','Bauxite','Limestone'],data_source:'DEMO_BUNDLED'},
 {id:'capesize',vessel_type:'Capesize',dwt:180000,cargo_capacity:172000,loa:292,beam:45,draft:18.2,laden_speed:14,ballast_speed:15,daily_opex:8200,daily_charter_rate:27000,loading_rate:45000,discharge_rate:38000,cargo_types:['Coal','Iron Ore','Bauxite','Limestone'],data_source:'DEMO_BUNDLED'},
];

export function getDemoMarketSignals(origin?: string, vesselType?: string): MarketSignals {
 const base=origin==='Brazil'?68.4:origin==='Indonesia'?61.8:origin==='South Africa'?64.7:origin==='USA Gulf'?71.2:65.96;
 return {freight_rate:base,fuel_price:620,demand_index:72.4,supply_index:65.1,port_congestion_index:42,demand_supply_pressure:7.3,observations:2062,data_classification:'DEMO_BUNDLED'};
}

function makeFeasibility(port: BackendPort,vessel: BackendVessel,cargoType:string,qty:number): BackendFeasibilityResult {
 const checks={draft:vessel.draft<=port.max_draft,loa:vessel.loa<=port.max_loa,beam:vessel.beam<=port.max_beam,cargo:port.cargo_types_supported.includes(cargoType),capacity:qty<=vessel.cargo_capacity,handling:vessel.discharge_rate>0};
 const reasons=Object.entries(checks).filter(([,ok])=>!ok).map(([k])=>`${k} check failed`);
 return {status:reasons.length?'FEASIBLE_WITH_WARNINGS':'FEASIBLE',port:{id:port.id,name:port.name},vessel:{id:vessel.id,vessel_type:vessel.vessel_type},cargo_type:cargoType,cargo_quantity:qty,checks,reasons,warnings:port.congestion_index>.5?['Elevated congestion exposure']:[],handling:{effective_loading_rate_tpd:Math.min(vessel.loading_rate,port.cargo_handling_rate),effective_discharge_rate_tpd:Math.min(vessel.discharge_rate,port.cargo_handling_rate),estimated_discharge_days:qty/Math.min(vessel.discharge_rate,port.cargo_handling_rate),estimated_loading_days:qty/Math.min(vessel.loading_rate,port.cargo_handling_rate)},restrictions:port.restrictions??[],data_source:'DEMO_BUNDLED'};
}

export function buildDemoIntegratedDecision(input:{originId:string;portId:string;cargoQuantity:number;cargoType:string;currentFreightRate:number;fuelPrice:number;vesselPreference?:string}): IntegratedDecisionResult {
 const port=DEMO_PORTS.find(p=>p.id===input.portId)??DEMO_PORTS[0];
 const vessel=DEMO_VESSELS.find(v=>v.vessel_type===input.vesselPreference)??DEMO_VESSELS.find(v=>v.cargo_capacity>=input.cargoQuantity)??DEMO_VESSELS[2];
 const f=makeFeasibility(port,vessel,input.cargoType,input.cargoQuantity);
 const contracts=[1,3,6,12].map((voyages,i)=>{const discount=i*.018;const rate=input.currentFreightRate*(1-discount);const freight=input.cargoQuantity*rate;const fuel=input.cargoQuantity*.18*input.fuelPrice;const total=freight*(voyages===1?1:Math.min(voyages,6)*.96)*1.03;return {voyages,contract:`${voyages}-voyage`,label:`${voyages} Voyage`,effective_rate:+rate.toFixed(2),forecast_rate:+(rate*1.02).toFixed(2),confidence:+(.93-i*.04).toFixed(2),lower_bound:+(rate*.96).toFixed(2),upper_bound:+(rate*1.05).toFixed(2),freight_cost:Math.round(freight),fuel_cost:Math.round(fuel),congestion_idle_cost:Math.round(total*.012),uncertainty_cost:Math.round(total*.01),commitment_cost:Math.round(total*.008),total_cost:Math.round(total),cost_per_ton:+(total/input.cargoQuantity).toFixed(2),discount_pct:+(discount*100).toFixed(1),savings_vs_spot:Math.round(input.cargoQuantity*(input.currentFreightRate-rate))};});
 const best=contracts.reduce((a,b)=>b.cost_per_ton<a.cost_per_ton?b:a);
 const congestionLevel=port.congestion_index>.7?'CRITICAL':port.congestion_index>.5?'HIGH':port.congestion_index>.3?'MODERATE':'LOW';
 const congestion:BackendCongestionResult={port_id:port.id,port_name:port.name,congestion_index:port.congestion_index,congestion_level:congestionLevel,berth_utilization:port.berth_utilization,queue_factor:1.2,waiting_time_days:port.anchorage_wait_time,uncongested_wait_days:.4,congestion_delay_days:.5,additional_idle_days:.5,daily_cost_basis_usd:vessel.daily_charter_rate,congestion_cost_usd:vessel.daily_charter_rate*.5,reference_index_uncongested:.2,data_source:'DEMO_BUNDLED'};
 const voyage:BackendVoyageResult={origin:DEMO_ORIGINS.find(o=>o.id===input.originId)??DEMO_ORIGINS[0],destination_port:port,vessel:{id:vessel.id,vessel_type:vessel.vessel_type,dwt:vessel.dwt},cargo_type:input.cargoType,cargo_quantity:input.cargoQuantity,feasibility:f,distance:{distance_nm:5200},duration_days:{sailing_laden:16.2,ballast:15.4,loading:2.1,discharge:2.8,port_waiting:.8,congestion_delay:.5,port_turn_overhead:.7,total_voyage_duration:23.1},congestion,assumptions:{data:'bundled demonstration assumptions'}};
 return {recommendation:{contract:best.label,voyages:best.voyages,vessel_type:vessel.vessel_type,port:port.name,reason:'Bundled decision simulation favors the lowest risk-adjusted delivered cost.'},contract_options:contracts,vessel_ranking:DEMO_VESSELS.map((v,i)=>({vessel_id:v.id,vessel_type:v.vessel_type,score:+(94-i*6).toFixed(1),cargo_capacity:v.cargo_capacity,draft:v.draft,loa:v.loa,beam:v.beam,daily_charter_rate:v.daily_charter_rate,feasibility:makeFeasibility(port,v,input.cargoType,Math.min(input.cargoQuantity,v.cargo_capacity))})),selected_vessel:vessel,voyage,idle_management:{trigger:'Port congestion above normal',current_idle_days:.8,recommended_strategy:'Secure berth window + retain alternate port option',alternatives:DEMO_PORTS.filter(p=>p.id!==port.id).map(p=>({port_id:p.id,port_name:p.name,congestion_level:p.congestion_index>.5?'HIGH':p.congestion_index>.3?'MODERATE':'LOW',congestion_index:p.congestion_index,reposition_days:1.2,reposition_cost_usd:18500,idle_days_avoided:.7,feasibility:'FEASIBLE',strategy:'Alternate discharge window'})),deadheading_note:'Keep one alternate port available to reduce congestion exposure.'},risk_alerts:[{level:'MEDIUM',type:'CONGESTION',message:'Bundled congestion index indicates moderate waiting-time exposure.'},{level:'LOW',type:'MARKET',message:'Freight demand is modestly above vessel supply in this demo scenario.'}],data_provenance:{market_history:'Bundled synthetic SIH-style history',port_master:'Bundled demonstration port master',route_distance:'Bundled route-distance assumption',live_port_feed:false}};
}
